#!/usr/bin/env bash
# Prerequisites:
# - export DOCKER_HOST accordingly
# - performance-monitor is under $HOME/projects/performance-monitor
#   (change in below if needed)
# - images generated by performance-monitor are under $PERF_DIR/img
# - Output files are under /tmp/data
#   (change in below if needed)
# - take_results assumes that `ssh $PI_HOST` succeeds; PI_HOST defaults to agilegw
#   (export PI_HOST accordingly and modify ~/.ssh/config if needed)
# -

DATA_ROOT_DIR=/tmp/data
PERF_DIR=$HOME/git/agile/performance-monitor
ARCH=x86_64
ADDR=http://localhost:1880
PI_HOST=localhost
